version: "3.3"

services:
  accountservice:
    build:
      context: .
      dockerfile: accountservice/Dockerfile
    image: gotter_accountservice
    ports:
      - "6767:6767"
    deploy:
      replicas: 1
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12202"
        gelf-compression-type: "none"

  vipservice:
    build:
      context: .
      dockerfile: vipservice/Dockerfile
    image: gotter_vipservice
    ports:
      - "6868:6868"
    deploy:
      replicas: 2

  quotesservice:
    image: eriklupander/quotes-service:latest
    deploy:
      replicas: 1

  rabbitmq:
    build:
      context: support/rabbitmq
    image: gotter_rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"

  configserver:
    build:
      context: support/config-server
    image: gotter_configservice
    ports:
      - "8888:8888"

  gelftail:
    build:
      context: gelftail
    image: gotter_gelftail
    ports:
      - "12202:12202/udp"

  swarmvisualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
